name: Build and deploy Python app to Azure Web App - parthbhanderi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Make run.sh executable
      - name: Make run.sh executable
        run: chmod +x run.sh

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Make run.sh executable
        run: chmod +x run.sh

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0C0BDC2E61574D0CA03B829AC1A9DBBA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6ABA8D37F2DF42A0A16FCAC94402CD33 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E078F6B01BB2468FA6191B8DD771AC84 }}

      - name: Configure App Service settings
        uses: Azure/appservice-settings@v1
        with:
          app-name: 'parthbhanderi'
          app-settings-json: |
            [
              {
                "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                "value": "true"
              },
              {
                "name": "STARTUP_COMMAND",
                "value": "./run.sh"
              }
            ]

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'parthbhanderi'
          slot-name: 'Production'

      # Optional: Run run.sh after deployment
      - name: Execute run.sh
        run: |
          chmod +x run.sh
          ./run.sh
