# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - parthbhanderi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_d3c76c1dd83b427a9c57a3b2135d441b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7db51d7c52ec42f894966a307b4d375a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_d3c76c1dd83b427a9c57a3b2135d441b }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'parthbhanderi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_21ef1e5578ff466cb7cd7235f0d8b832 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_d3c76c1dd83b427a9c57a3b2135d441b }}/appsvc/staticsite:${{ github.sha }}'