name: Build and deploy container app to Azure Web App - parthbhanderi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: mcr.microsoft.com
        username: ${{ secrets.AZURE_CONTAINER_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_PASSWORD }}

    - name: Build and push container image
      uses: docker/build-push-action@v5
      with:
        context: .  # Ensure correct build context
        file: ./Dockerfile  # Explicitly specify Dockerfile location
        push: true
        tags: mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'parthbhanderi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'